#!/bin/bash
#!/usr/bin/bash

echo "Entrada: a / Saída Esperada: Valido"
echo "a" | ./cov
echo "Entrada: abcdefg / Saída Esperada: Invalido"
echo "abcdefg" | ./cov
echo "Entrada: 0 / Saída Esperada: Invalido"
echo 0 | ./cov
echo "Entrada: abc4 / Saída Esperada: Valido"
echo "abc4" | ./cov
echo "Entrada: abc@ / Saída Esperada: Invalido"
echo "abc@" | ./cov
echo "Entrada: A1b2C3 / Saída Esperada: Valido"
echo "A1b2C3" | ./cov
gcov -b identifier.c

echo " "

echo "Cppcheck"
cppcheck --enable=all --suppress=missingIncludeSystem identifier.c

echo " "

echo "Valgrind"
valgrind --leak-check=full --show-leak-kinds=all echo "abc" | ./identifier

echo " "

echo "Sanitize"
echo "Entrada: a / Saída Esperada: Valido"
echo "a" | ./identifier_sanitize
echo "Entrada: abc4 / Saída Esperada: Valido"
echo "abc4" | ./cov
