#!/bin/bash
#!/usr/bin/bash

echo "Entrada: a"
echo "Saída Esperada: Valido"
echo "a" | ./cov
echo ""
echo "Entrada: abcdefg"
echo "Saída Esperada: Invalido"
echo "abcdefg" | ./cov
echo ""
echo "Entrada: 0"
echo "Saída Esperada: Invalido"
echo 0 | ./cov
echo ""
echo "Entrada: abc4"
echo "Saída Esperada: Valido"
echo "abc4" | ./cov
echo ""
echo "Entrada: abc@"
echo "Saída Esperada: Invalido"
echo "abc@" | ./cov
echo ""
echo "Entrada: A1b2C3"
echo "Saída Esperada: Valido"
echo "A1b2C3" | ./cov
gcov -b identifier.c

echo " "

echo "Cppcheck"
cppcheck --enable=all --suppress=missingIncludeSystem identifier.c

echo " "

echo "Valgrind"
valgrind --leak-check=full --show-leak-kinds=all echo "abc" | ./identifier

echo " "

echo "Sanitize"
echo "Entrada: a / Saída Esperada: Valido"
echo "a" | ./identifier_sanitize
echo "Entrada: abc4 / Saída Esperada: Valido"
echo "abc4" | ./cov
